name: macOS 14 Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    env:
      MACFUSE_VERSION: 4.8.2
      MOOSEFS_VERSION: 3.0.118

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: |
          curl -L -o macfuse.dmg https://github.com/macfuse/macfuse/releases/download/macfuse-${{ env.MACFUSE_VERSION }}/macfuse-${{ env.MACFUSE_VERSION }}.dmg
          hdiutil attach macfuse.dmg
          sudo installer -pkg /Volumes/macFUSE/Install\ macFUSE.pkg -target /
          cd repo
          git fetch --tags
          git checkout tags/v${{ env.MOOSEFS_VERSION }}
          ./macosx_build.sh
          ./macosx/makepkg.sh

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./moosefs-3.0.118-1.pkg
          overwrite: true

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release
          path: ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: 3.0.118
          files: ./release-assets/*.pkg
          draft: false
          prerelease: false

